# Generated by Django 2.0.5 on 2018-05-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, unique=True, verbose_name='主机名')),
                ('network_ip', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='外网IP')),
                ('inner_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='内网IP')),
                ('system', models.CharField(blank=True, max_length=128, null=True, verbose_name='系统版本')),
                ('cpu', models.CharField(blank=True, max_length=64, null=True, verbose_name='CPU')),
                ('memory', models.CharField(blank=True, max_length=64, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=256, null=True, verbose_name='硬盘')),
                ('mac', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='MAC地址')),
                ('bandwidth', models.IntegerField(blank=True, default='1', null=True, verbose_name='外网带宽')),
                ('platform', models.CharField(choices=[('物理机', '物理机'), ('虚拟机', '虚拟机'), ('阿里云', '阿里云'), ('其他', '其他')], max_length=128, verbose_name='平台')),
                ('region', models.CharField(choices=[('合肥', '合肥'), ('武汉', '武汉'), ('香港', '香港'), ('其他', '其他')], max_length=128, verbose_name='区域')),
                ('branch', models.CharField(choices=[('001业务线', '001业务线'), ('003业务线', '002业务线'), ('004业务线', '004业务线')], max_length=128, verbose_name='业务线')),
                ('Instance_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='实例ID')),
                ('ps', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('port', models.IntegerField(blank=True, default='22', null=True, verbose_name='登录端口')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产管理',
                'verbose_name_plural': '资产管理',
                'db_table': 'AssetInfo',
            },
        ),
        migrations.CreateModel(
            name='AssetLoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('username', models.CharField(blank=True, default='root', max_length=64, null=True, verbose_name='用户名')),
                ('password', models.CharField(blank=True, max_length=256, null=True, verbose_name='密码')),
                ('private_key', models.FileField(blank=True, null=True, upload_to='upload/privatekey/%Y%m%d25915', verbose_name='私钥')),
                ('ps', models.CharField(blank=True, max_length=10240, null=True, verbose_name='备注')),
                ('ctime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资产用户',
                'verbose_name_plural': '资产用户',
                'db_table': 'AssetLoginUser',
            },
        ),
        migrations.CreateModel(
            name='AssetProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.CharField(max_length=128, verbose_name='资产项目')),
                ('ps', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '资产项目',
                'verbose_name_plural': '资产项目',
                'db_table': 'AssetProject',
                'permissions': {('read_assetproject', '只读资产项目'), ('cmd_assetproject', '执行资产项目')},
            },
        ),
        migrations.AddField(
            model_name='assetloginuser',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='asset.AssetProject', verbose_name='资产项目'),
        ),
        migrations.AddField(
            model_name='assetinfo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='asset.AssetProject', verbose_name='资产项目'),
        ),
        migrations.AddField(
            model_name='assetinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_name', to='asset.AssetLoginUser', verbose_name='登录用户'),
        ),
    ]
