# Generated by Django 2.0.5 on 2018-05-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetinfo',
            name='is_active',
            field=models.CharField(choices=[(0, '在线'), (1, '下线'), (2, '未知'), (3, '故障'), (4, '备用')], default=0, max_length=64, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='assetloginuser',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='upload/privatekey/%Y%m%d37342', verbose_name='私钥'),
        ),
    ]
