# Generated by Django 2.0.5 on 2018-05-18 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20180517_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=128, verbose_name='业务')),
                ('ps', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '资产业务',
                'verbose_name_plural': '资产业务',
                'db_table': 'AssetBusiness',
            },
        ),
        migrations.AlterField(
            model_name='assetloginuser',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='upload/privatekey/%Y%m%d55191', verbose_name='私钥'),
        ),
        migrations.AddField(
            model_name='assetinfo',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_business', to='asset.AssetBusiness', verbose_name='资产业务'),
        ),
    ]
