# Generated by Django 2.0.5 on 2018-05-17 14:45

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='工具名称')),
                ('tool_script', models.TextField(blank=True, null=True, verbose_name='脚本')),
                ('tool_run_type', models.CharField(choices=[('shell', 'shell'), ('python', 'python'), ('yml', 'yml')], max_length=24, verbose_name='脚本类型')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='工具说明')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工具',
                'verbose_name_plural': '工具',
                'db_table': 'Tools',
            },
        ),
        migrations.CreateModel(
            name='ToolsResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(unique=True, verbose_name='任务ID')),
                ('add_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建者')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'db_table': 'ToolsResults',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='变量组名字')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('vars', jsonfield.fields.JSONField(blank=True, default={}, null=True, verbose_name='变量')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('utime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('assets', models.ManyToManyField(blank=True, related_name='asset', to='asset.AssetInfo', verbose_name='关联资产')),
            ],
            options={
                'verbose_name': '变量组',
                'verbose_name_plural': '变量组',
                'db_table': 'Variable',
            },
        ),
    ]
